---
- hosts: kube_node
  gather_facts: false
  become: true
  tasks:
    - name: Install longhorn dependencies
      apt:
        name:
          - grep
          - curl
          - bash
          - util-linux
          - open-iscsi
          - nfs-common
          - dmsetup
          - gawk
        state: present

    - name: Ensure iSCSI services are enabled and started
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - open-iscsi
        - iscsid

    - name: Ensure iscsi_tcp kernel module is loaded
      ansible.builtin.modprobe:
        name: iscsi_tcp
        state: present
