roles:
  - name: mrlesmithjr.netplan
collections:
 - name: https://github.com/kubernetes-sigs/kubespray
   type: git
   version: 0d88532f3d3981f3068169ce79af686d6a0aef9d
#   version: v2.29.0
 - name: kubernetes.core
   version: "6.5.0"
