roles:
  - name: mrlesmithjr.netplan
collections:
 - name: https://github.com/kubernetes-sigs/kubespray
   type: git
   version: v2.31.0
#   version: v2.29.0
 - name: kubernetes.core
   version: "6.5.0"
